### PR TITLE
Ignore responses to missing remote calls.

### LINKED ISSUE #86: `PageWidget.action_respond` is sometimes invoked with a nonexistent response identifier
`PageWidget.connectionLost` resets all the remote calls but sometimes a response action is delivered after this has happened, which fails trying to callback a nonexistent call.

### PR DESCRIPTION
**Pull request by jonathanj**
Fixes #86.

### CODE REVIEW

File: nevow/js/Nevow/Athena/__init__.js [hunk 1]
```diff
@@ -105,6 +105,15 @@ Nevow.Athena.PageWidget.methods(
         var d = self.remoteCalls[responseId];
         delete self.remoteCalls[responseId];
 
+        if (d === undefined) {
+            // If the transport is running then something strange has happened,
+            // otherwise just do nothing.
+            if (self.deliveryChannel.running) {
+                Divmod.msg('Received response to missing call: ' + responseId);
```
Comment (mithrandi) [inline nevow/js/Nevow/Athena/__init__.js]: "missing" is a little mysterious if you're not deeply familiar with this bit of the code already; how about "unknown or already-responded call" instead?

**Comment by mithrandi** [comment]
:+1:
